apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  FRONTEND_URL: {{ .Values.backend.env.FRONTEND_URL | quote }}
  API_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
  NEXT_PUBLIC_CHATKIT_DOMAIN_KEY: {{ .Values.frontend.env.NEXT_PUBLIC_CHATKIT_DOMAIN_KEY | quote }}
