apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "todo-chatbot.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.frontend.selectorLabels" . | nindent 4 }}
