apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.backend.secrets.OPENAI_API_KEY | b64enc | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.backend.secrets.BETTER_AUTH_SECRET | b64enc | quote }}
